### ISSUE TITLE
AmazonS3Service Bean Error

### ISSUE THREAD

**Issue by redwolfgang24** [agorapulse/grails-aws-sdk#117]
What's the problem with the configuration why aws s3 service is not working always giving an error.
Please help me about this issue, thanks in advance. Below is my configuration and sample code.

**_build.gradle_**
```
buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core" }
        maven { url "http://dl.bintray.com/agorapulse/libs" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "org.grails.plugins:hibernate5:7.0.0"
        classpath "org.grails.plugins:views-gradle:2.0.0.BUILD-SNAPSHOT"
    }
}

version "0.1"
group "sample"

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"war"
apply plugin:"org.grails.grails-web"
apply plugin:"org.grails.plugins.views-json"
apply from: "${rootProject.projectDir}/gradle/codenarc.gradle"

repositories {
    maven { url "https://repo.grails.org/grails/core" }
    maven { url "http://dl.bintray.com/agorapulse/libs" }
}

dependencies {
    compile "org.grails.plugins:aws-sdk-s3:2.2.12"
    compile "com.amazonaws:aws-java-sdk-s3:1.11.592"
}
```

**_S3ResourceService.groovy_**
```
package com.sample

import com.sample.common.AbstractValidateAndSaveService
import com.sample.exception.InvalidFileException
import com.sample.types.S3ResourceStatus
import grails.gorm.transactions.Transactional
import grails.plugin.awssdk.s3.AmazonS3Service
import org.springframework.web.multipart.MultipartFile

@Transactional
class S3ResourceService extends AbstractValidateAndSaveService {

	AmazonS3Service amazonS3Service

	S3Resource uploadContent(MultipartFile multipartFile, S3Resource s3Resource) {
		validateMultipartFile()
		amazonS3Service.storeMultipartFile(
			s3Resource.bucket.bucketName,
			s3Resource.key,
			multipartFile
		)
		return create(s3Resource)
	}

	S3Resource create(S3Resource s3Resource) {
		s3Resource.status = S3ResourceStatus.READY
		validateAndSave(s3Resource)
		return s3Resource
	}

	private void validateMultipartFile(MultipartFile multipartFile) {
		if (multipartFile && multipartFile.bytes.size() < 1) {
			throw new InvalidFileException()
		}
	}
}
```

```Grails application running at http://localhost:8080 in environment: development
2021-05-10 02:25:12.524 ERROR --- [nio-8080-exec-5] o.g.web.errors.GrailsExceptionResolver   : NoSuchMethodError occurred when processing request: [POST] /api/v1/s3resource/resume
org/apache/http/conn/ssl/SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V (loaded from file:/home/larry/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.3.3/18f4247ff4572a074444572cee34647c43e7c9c7/httpclient-4.3.3.jar by sun.misc.Launcher$AppClassLoader@3e62596f) called from class com.amazonaws.http.conn.ssl.SdkTLSSocketFactory (loaded from file:/home/larry/.gradle/caches/modules-2/files-2.1/com.amazonaws/aws-java-sdk-core/1.11.500/81e6bc7d745a51e5a281b2f0197a0fe1be29c201/aws-java-sdk-core-1.11.500.jar by sun.misc.Launcher$AppClassLoader@3e62596f).. Stacktrace follows:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.welinktalent.api.v1.S3ResourceController': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 's3ResourceService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsSdkS3AmazonS3Service': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org/apache/http/conn/ssl/SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V (loaded from file:/home/larry/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.3.3/18f4247ff4572a074444572cee34647c43e7c9c7/httpclient-4.3.3.jar by sun.misc.Launcher$AppClassLoader@3e62596f) called from class com.amazonaws.http.conn.ssl.SdkTLSSocketFactory (loaded from file:/home/larry/.gradle/caches/modules-2/files-2.1/com.amazonaws/aws-java-sdk-core/1.11.500/81e6bc7d745a51e5a281b2f0197a0fe1be29c201/aws-java-sdk-core-1.11.500.jar by sun.misc.Launcher$AppClassLoader@3e62596f).
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:73)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.rest.RestTokenValidationFilter.processFilterChain(RestTokenValidationFilter.groovy:121)
        at grails.plugin.springsecurity.rest.RestTokenValidationFilter.doFilter(RestTokenValidationFilter.groovy:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.rest.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.groovy:139)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.rest.RestLogoutFilter.doFilter(RestLogoutFilter.groovy:82)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
        at grails.plugin.springsecurity.web.filter.DebugFilter.invokeWithWrappedRequest(DebugFilter.groovy:103)
        at grails.plugin.springsecurity.web.filter.DebugFilter.doFilter(DebugFilter.groovy:70)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter.doFilterInternal(GrailsHttpPutFormContentFilter.groovy:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.rest.RestTokenValidationFilter.processFilterChain(RestTokenValidationFilter.groovy:121)
        at grails.plugin.springsecurity.rest.RestTokenValidationFilter.doFilter(RestTokenValidationFilter.groovy:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.rest.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.groovy:139)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.rest.RestLogoutFilter.doFilter(RestLogoutFilter.groovy:82)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:823)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 's3ResourceService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsSdkS3AmazonS3Service': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org/apache/http/conn/ssl/SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V (loaded from file:/home/larry/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.3.3/18f4247ff4572a074444572cee34647c43e7c9c7/httpclient-4.3.3.jar by sun.misc.Launcher$AppClassLoader@3e62596f) called from class com.amazonaws.http.conn.ssl.SdkTLSSocketFactory (loaded from file:/home/larry/.gradle/caches/modules-2/files-2.1/com.amazonaws/aws-java-sdk-core/1.11.500/81e6bc7d745a51e5a281b2f0197a0fe1be29c201/aws-java-sdk-core-1.11.500.jar by sun.misc.Launcher$AppClassLoader@3e62596f).
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByName(AbstractAutowireCapableBeanFactory.java:1452)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1391)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
        ... 64 common frames omitted
```

**Comment by musketyr** [comment]
Hi, this looks like a issue with versions of Apache HTTP client. Can you run 

`./gradlew classes --scan`

And paste the link to the scan page?

**Comment by redwolfgang24** [comment]
@musketyr This is what I got after running those command.

```
Welcome to Gradle 5.1.1!

Here are the highlights of this release:
 - Control which dependencies can be retrieved from which repositories
 - Production-ready configuration avoidance APIs

For more details see https://docs.gradle.org/5.1.1/release-notes.html

Starting a Gradle Daemon, 5 busy Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'welinktalent'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download build-scan-plugin.jar (com.gradle:build-scan-plugin:2.1)
      > Could not get resource 'https://repo.grails.org/grails/core/com/gradle/build-scan-plugin/2.1/build-scan-plugin-2.1.jar'.
         > Could not GET 'https://repo.grails.org/grails/core/com/gradle/build-scan-plugin/2.1/build-scan-plugin-2.1.jar'.
            > repo.grails.org: Name or service not known

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 41s
```

This is also the version of HTTP I use.
```
compile 'org.apache.httpcomponents:httpcore:4.3.3'
compile 'org.apache.httpcomponents:httpclient:4.3.3'
```

**Comment by redwolfgang24** [comment]
@musketyr I'm able to resolve the issue by upgrading HTTP version. Thank you @musketyr

**Comment by musketyr** [comment]
you're welcome!
